Add show player coordinates option
CptWesley/NewWorldMinimap pull request #143
Opened 2021-10-30 09:25 UTC by ryantam626

For debugging purposes.

Also ignore some files generated by my IDE.

2021-10-30 09:37 UTC, CptWesley commented
Haven't tried this myself yet, but does this play nicely with the different minimap shapes?

2021-10-30 10:27 UTC, ryantam626 commented
Nope, it most certainly does not. It's currently sits at the top right corner.

Do you want me to move it to the center, just below the player's marker (when map is not panned)

2021-10-30 10:50 UTC, CptWesley commented
I think that might be better. That way it should work for all kinds of weird minimap shapes.

2021-10-30 11:13 UTC, ryantam626 commented
Gotcha - updated.

Panned
![image](https://user-images.githubusercontent.com/8895126/139530613-d1f2f771-ee52-4b89-acf4-8020b4ab34bd.png)


Overlay, diamond
![image](https://user-images.githubusercontent.com/8895126/139530622-8d9e9ff1-6dc5-450f-9a97-f562f3d45442.png)

2021-10-30 19:54 UTC, pvdstel requested changes
Since the setting you added (`showPlayerCoordinates`) affects rendering, it should be added to the [`updateOn` array](https://github.com/ryantam626/NewWorldMinimap/blob/ebbdaefcaed71b1d1f0dc89bceff0e7443016a6c/overwolf/src/Minimap/useMinimapRenderer.ts#L270) (preferably with the alphabetic sorting). Adding the value `appContext.settings.showPlayerCoordinates` will automatically trigger a re-render, showing (or hiding) the coordinates.

---

If combined with navigation, the text starts looking quite funky. Haven't found the exact cause yet. I think it's `strokeStyle` from `drawMapNavigation`, which may have to be reset.

![image](https://user-images.githubusercontent.com/17430732/139556584-6cf64bec-9a1d-410b-8615-2ca1a49f4eed.png)

---

It doesn't play nice with `iconScale`. I'm not sure if this is too relevant, since I essentially consider this a debug setting. What do you think @CptWesley ?

![image](https://user-images.githubusercontent.com/17430732/139556596-2af306e1-cf16-4794-914f-93c8c383121e.png)

---

The rendering changes depending on if `showText` is enabled. When it's on, it starts looking like this:

![image](https://user-images.githubusercontent.com/17430732/139556698-4d327977-ef16-415c-ac68-25a87efe0ab5.png)

Haven't figured out the reason for that happening yet. It's certainly strange. It does make the text look exactly like the other text, so I imagine the styling/positioning there plays a role.

---

Some discussion about the location of the implementation: I think the current implementation (drawing the coordinates in a separate file) is fine. Some alternatives to consider, maybe for the future:

- Adding the coordinate rendering to `drawMapPlayer`.
- Moving the condition for rendering to `useMinimapRenderer/draw`. That would skip the function call and the deconstruction of arguments, and would make the added field to `MapRenderParameters` unnecessary.

Nothing you need to change here, just me thinking out loud 😄

---

A final point to think about, also not really an actionable point: this setting is a global setting, so it technically doesn't belong in the _This window_ tab in the app settings. I'd prefer to add another tab, _Advanced_ (or something) where this checkbox can live, especially if we consider this a debug setting. That tab could then also have the magical _Reset all settings_ button. But that's just to think about for the future.

2021-10-30 19:54 UTC, pvdstel commented on overwolf/src/Minimap/drawPlayerCoordinates.ts
> +        console.log(textX, textY);
This log should be removed.

2021-10-30 22:33 UTC, ryantam626 commented
Good spots @pvdstel - thanks!

Screeshot after latest updates.
Pan + nav on.
![image](https://user-images.githubusercontent.com/8895126/139560173-0b89af23-02c6-4a03-b065-0327de277180.png)

Show text on.
![image](https://user-images.githubusercontent.com/8895126/139560183-6b42aa05-b5dd-4411-b1e5-284c2139f647.png)

Non-default icon scale.
![image](https://user-images.githubusercontent.com/8895126/139560211-192d4dce-211a-4455-aabf-1a49de86d4a7.png)

Non-default icon scale + show text on.
![image](https://user-images.githubusercontent.com/8895126/139560230-81d97efe-447b-4df1-81d3-fd6b49201f24.png)

In-game truncated map style.
![image](https://user-images.githubusercontent.com/8895126/139560240-e5f4029c-73dd-4bb7-86d3-3738af48ce7d.png)

2021-10-31 08:03 UTC, CptWesley commented
Your latest screenshots seem to somehow override the strokestyle of the icon text. Perhaps we should just extract the style-setting pieces of code to seperate functions so we can just do something like `setTextStyle()` and `setLineStyle()` or something similar to avoid these kind of issues in the future.

2021-10-31 08:09 UTC, merged